### ISSUE TITLE
Fountain JS ToDo

### ISSUE THREAD

**Issue by Swiip** [FountainJS/generator-fountain-webapp#1]
The steps I'll list here can exceed the perimeter of this generator but I have to put this somewhere. The granularity and the order of the steps can (and will) evolve over time. Don't hesitate to argue or add something.
- [x] Makes things works with NPM
- [x] Readme fountain-webapp
- [x] Contributing fountain-webapp
- [x] Design fountain-webapp
- [x] Optimization task for Webpack
- [x] Optimization task for SystemJS
- [x] Optimization task for Inject
- [x] Handling styles with Webpack
- [x] Handling styles for inject and SystemJS
- [x] Support for TypeScript and plain JS
- [x] Support for CSS, SASS and LESS
- [x] Script the release process
- [x] Initiate tests
- [x] Initiate sample app
- [x] Wire up Travis

Later / Macro...
- [ ] Move generator-gulp-angular repo inside FountainJS
- [ ] Create a home website with doc & blog, a bit like yeoman.io to be honest
- [ ] Create a Electron multiplatform app to run the generator

Blog post to write in parallel. To be published on the website when online.
- [x] Why (still) Gulp
- [ ] Fountain generators approach
- [ ] Web Dev Experience

**Comment by Swiip** [comment]
At this point, `gulp serve`, `gulp test` and `gulp serve:dist` should work for every combination. It will still have bugs but it should ^^. Tests will soon be needed. @zckrs you seemed to be inspired about that, it will soon bu needed.

But that's only for JS and showing an Hello World. I'm starting to look at CSS management now.

**Comment by Swiip** [comment]
Just released a 0.2.1 where all options and all gulp tasks should work \o/

I intend to work on a sample app which each framework. I think of a single page listing the techs like before. No CSS framework. Loading data from an external JSON, not directly inside a controller.

I'll also makes it optional so I'll keep the hello world version and override it only if the option is chosen.

After that: all main options, all main tasks, it will be time for some communication :)

**Comment by Swiip** [comment]
Following the work of welcoming @micaelmbagira, I listed a lot of tasks. Most of them will be needed for releasing a beta version (and starting communication).

Must work for any option combinaison:
- gulp dev task with server and livereload
- gulp build task which build an optimized version of the site
- gulp test task which runs the unit tests

For all combinations, we implies to have:
- A working website with no errors
- No (not one) linter error
- Successful tests

Tasks:
- Misc
- [x] Fix as many bugs as possible
- [x] Remove last `path.join` in gulp and conf in profit of `conf.path.*`
- [x] Check the livereload mechanism for each type of files (and HMR for React / Webpack)
- Enhancement on inner tools
- [ ] Add possibility to order and comment the output of json2js
- [ ] Study the possibility of not having configuration in HTML files with useref (looking at transformPath option)
- Better tests
- [ ] Add unit tests in techs templates
- [ ] Add unit tests on the generators
- [x] Upgrade to PhantomJS 2.1 in generator-fountain-karma
- [x] Find an integration test solution, should at least cover framework / modules / js (= 27) combinations
- Enhance Angular 2
- [x] Remove axios in profit of ng2 $http equivalent
- [ ] Using html template files and check configuration (especially for unit tests)
- [x] Better ng2 tests like in `angular-cli` using `angular2/testing`
- Better linter configuration
- [ ] Renaming generator-fountain-eslint for generator-fountain-javascript
- [x] Moving Babel configuration in generator-fountain-javascript
- [x] Use of XO eslint configuration everywhere (generators and generated projects with es5 or es2015)
- [ ] Renaming generator-fountain-tslint for generator-fountain-typescript
- [x] Migration from TSD to typings
- [ ] Trying to find a externalized / standard / shared tslint configuration

**Comment by Swiip** [comment]
If all is not checked, I think we're passed that type of todo list for Fountain, I close this for now. A last ping to @micaelmbagira to remember some leads of enhancement possible.

**Comment by odyright** [comment]
is the electron generator ready?
